Use java fx coordinates for hit test
micheljung/fxstage pull request #6
Opened 2021-07-04 11:49 UTC by 1-alex98

2021-07-04 11:51 UTC, 1-alex98 commented
Main change is that mouse and window coorinates are taken from stage and mouse coordinates from ROBOT

2021-07-04 11:55 UTC, 1-alex98 commented
Fixes #5

2021-07-04 11:56 UTC, 1-alex98 commented on src/main/java/ch/micheljung/fxwindow/DecorationWindowProcedure.java
> +    Point2D mousePosition = ROBOT.getMousePosition();
use javafx robot for mouse

2021-07-04 11:56 UTC, 1-alex98 commented on src/main/java/ch/micheljung/fxwindow/DecorationWindowProcedure.java
> +    return new LRESULT(hitTest(new Rect(windowController.getStage()), new Point(mousePosition), windowController, features.isAllowTopResize()).windowsValue);
use javafx stage for window

2021-07-04 11:57 UTC, 1-alex98 commented
When testing it it's smooth and works

2021-07-08 07:03 UTC, micheljung requested changes

2021-07-08 07:03 UTC, micheljung commented on src/main/java/ch/micheljung/fxwindow/DecorationWindowProcedure.java
> +  static HitTestResult hitTest(Rect window, Point mouse, WindowController controller, boolean allowTopResize) {
```suggestion
  private static HitTestResult hitTest(Rect window, Point mouse, WindowController controller, boolean allowTopResize) {
```

2021-07-08 07:03 UTC, micheljung commented on src/main/java/ch/micheljung/fxwindow/DecorationWindowProcedure.java
> +  public static final Robot ROBOT = new Robot();
```suggestion
  private static final Robot robot = new Robot();
```
Only constant-like fields are UPPERCASE

2021-07-08 07:03 UTC, micheljung commented on src/main/java/ch/micheljung/fxwindow/DecorationWindowProcedure.java
> +@Log4j2
Why? I don't see it being used.
```suggestion
```

Remove import, too.

2021-07-09 15:59 UTC, 1-alex98 commented
ok yeah sure gonna fix those... I was foremost interested in an evaluation of my approach

2021-07-16 11:09 UTC, micheljung requested changes

2021-07-16 11:09 UTC, micheljung commented on src/main/java/ch/micheljung/fxwindow/DecorationWindowProcedure.java
> +  public static final Robot robot = new Robot();
```suggestion
  private static final User32Ex user32Ex = User32Ex.INSTANCE;
  private static final Robot robot = new Robot();

  public static final LRESULT LRESULT_ZERO = new LRESULT(0);
```

2021-07-26 11:30 UTC, micheljung approved these changes

2021-08-25 16:01 UTC, merged

2021-09-03 10:20 UTC, 1-alex98 commented
You have to make a new tag I guess @micheljung

2021-10-19 20:15 UTC, micheljung commented
@1-alex98 I finally managed to release 0.8.1 to maven central